services:
    postgres:
        container_name: postgres_db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - '5432:5432'
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
